//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swd.BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Easyness { get; set; }
        public Nullable<double> Job { get; set; }
        public Nullable<double> Prestige { get; set; }
        public Nullable<double> Financies { get; set; }
        public Nullable<double> Fun { get; set; }
    }
}
